<a href="https://colab.research.google.com/github/lavisha1309/Lavisha-Rego/blob/main/Activity8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
newarr=arr.reshape(-1)
print("Flattened array:",newarr)


Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
rev_arr = newarr[::-1]
print("reversed array is:",rev_arr)

reversed array is: [12 11 10  9  8  7  6  5  4  3  2  1]


In [7]:
import numpy as np
arr_2d=np.random.randint(1, 101,size=(3,4))
print(arr_2d)


[[27 49 20 20]
 [86 50  2 80]
 [21 87 42  3]]


In [9]:
import numpy as np
arr1=np.array([[1,2,3], [7,8,9]])
arr2=np.random.randint(1, 101, size=(3, 4))
print("Data type of array 1:", arr1.dtype)
print("Data type of array 2:", arr2.dtype)

Data type of 1: int64
Data type of 2: int64


In [11]:
print("first 2 rows:",arr_2d[:2, :])

first 2 rows: [[27 49 20 20]
 [86 50  2 80]]


In [13]:
print("last 2 rows:",arr_2d[:, -2:])

last 2 rows: [[20 20]
 [ 2 80]
 [42  3]]


In [18]:
import numpy as np
arr=np.random.randint(1, 101, size=(2, 3, 4))
arr_3d=arr[0]
first_layer=arr_3d[0: :]
print("Original 3D array:\n", arr)
print("first layer:",first_layer)


Original 3D array:
 [[[29 69 78 17]
  [58 45 14  2]
  [11 96  3 59]]

 [[92 37 16  1]
  [70 20 77  8]
  [83 47 13 27]]]
first layer: [[29 69 78 17]
 [58 45 14  2]
 [11 96  3 59]]


In [25]:
import numpy as np
arr = np.random.randint(1, 101, size=(2, 3, 4))
third_ele=arr[1].flatten()[2]
print("3D array:\n", arr)
print("\n3rd element from 2nd layer:",third_ele)


3D array:
 [[[50 33 30 37]
  [31 41 66 74]
  [12 47 81 40]]

 [[48 24 46 15]
  [95  8 31 24]
  [74 83 76 30]]]

3rd element from 2nd layer: 46


In [31]:
total_sum = arr_2d.sum()
mean_value = arr_2d.mean()
print("Sum of all elements:",total_sum)
print("Mean of all elements:",mean_value)

Sum of all elements: 487
Mean of all elements: 40.583333333333336


In [32]:
arr_3d[arr_3d > 5] = 0
print("after replacing elements:", arr_3d)

after replacing elements: [[0 0 0 0]
 [0 0 0 2]
 [0 0 3 0]]


In [33]:
import numpy as np
arr=np.random.randint(1, 11, size=(2, 3, 4))
print("Original 3D array:\n",arr)
arr[arr > 5] = 0
print("\nModified 3D array (elements > 5 set to 0):\n", arr)


Original 3D array:
 [[[ 7  4  1  3]
  [ 5  3  6  7]
  [ 4  8  7  9]]

 [[ 8 10 10  3]
  [ 6  6  9  5]
  [ 5  6  3  6]]]

Modified 3D array (elements > 5 set to 0):
 [[[0 4 1 3]
  [5 3 0 0]
  [4 0 0 0]]

 [[0 0 0 3]
  [0 0 0 5]
  [5 0 3 0]]]


In [34]:
array_2df = np.array(arr_2d, dtype=float)
print("2D array as float:", array_2df)
print("New data type:", array_2df.dtype)

2D array as float: [[27. 49. 20. 20.]
 [86. 50.  2. 80.]
 [21. 87. 42.  3.]]
New data type: float64


In [47]:
arr_3d= np.random.randint(0,10,size=(2, 3, 4))
int_arr= arr_3d.astype(int)
print("\n",int_arr)


 [[[2 5 4 4]
  [9 6 3 2]
  [5 1 0 6]]

 [[6 7 5 6]
  [7 3 2 6]
  [8 4 6 9]]]


In [48]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])
print("a1:\n", a1)
print("a2:\n", a2)

a1:
 [[1 2 3]
 [4 5 6]]
a2:
 [[ 7  8  9]
 [10 11 12]]


In [49]:
b1 = np.random.randint(1, 11, size=(2, 2, 2))
b2 = np.random.randint(1, 11, size=(2, 2, 2))
b3 = np.random.randint(1, 11, size=(2, 2, 2))

print("b1:\n", b1)
print("\nb2:\n", b2)
print("\nb3:\n", b3)

b1:
 [[[8 5]
  [6 9]]

 [[9 5]
  [3 2]]]

b2:
 [[[9 2]
  [3 2]]

 [[2 7]
  [7 7]]]

b3:
 [[[1 4]
  [5 5]]

 [[7 7]
  [6 1]]]


In [50]:
b1_mod=b1*3
print("after modifying:\n", b1_mod)

after modifying:
 [[[24 15]
  [18 27]]

 [[27 15]
  [ 9  6]]]


In [51]:
print("Index and value in a1:")
for i in range(a1.shape[0]):
    for j in range(a1.shape[1]):
        print(f"({i},{j}): {a1[i,j]}")

Index and value in a1:
(0,0): 1
(0,1): 2
(0,2): 3
(1,0): 4
(1,1): 5
(1,2): 6


In [52]:
b3_flat = b3.flatten()
print("Flattened b3:\n", b3_flat)

Flattened b3:
 [1 4 5 5 7 7 6 1]


In [53]:
b3_reshaped=b3_flat.reshape(4, 2)
print("Reshaped (4,2):\n", b3_reshaped)

Reshaped (4,2):
 [[1 4]
 [5 5]
 [7 7]
 [6 1]]


In [56]:
multiple_4 = a1[a1 % 4 == 0]
print("Result:", multiple_4)

Result: [4]


In [58]:
x=np.array([1,3,5,7,9,11])
print(x)

[ 1  3  5  7  9 11]


In [59]:
ind=np.searchsorted(x, [4,8,10])
print("Insert indices for [4,8,10]:",ind)

Insert indices for [4,8,10]: [2 4 5]
